---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "db-config-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Db.Component }}"
    module: "{{ .Release.Name }}-{{ .Values.Db.Module }}"
data:
  PGDATA: "{{ .Values.Db.Postgres.MountPath }}/pgdata"
