apiVersion: v1
kind: Pod
metadata:
  name: test-configmap
spec:
  containers:
    - name: test-container
      image: alpine:3.8
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: TEST_TYPE
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: test.type
        - name: TEST_EXEC
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: test.exec
  restartPolicy: Never
