apiVersion: v1
kind: Secret
metadata:
  name: admin-access-encoded
type: Opaque
data:
  password.txt: U2VjcmV0NGV2ZXIK
  username.txt: YWRtaW4K
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-access-plain
type: Opaque
stringData:
  password.txt: Secret4Ever
  username.txt: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-access-file
type: Opaque
stringData:
  access.txt: | 
    User is admin
    Password is Secret4Ever
