apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: steakfulsets.food.training.sap
spec:
  group: food.training.sap
  names:
    kind: SteakfulSet
    listKind: SteakfulSetList
    plural: steakfulsets
    shortNames:
    - stks
    singular: steakfulset
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                steak:
                  type: object
                  properties:
                    cookLevel:
                      type: string
                    fat:
                      type: string
                    weight:
                      type: integer
                  required:
                  - weight
                  - cookLevel
                  - fat
              required:
              - steak          
      additionalPrinterColumns:
      - name: Weight
        type: integer
        description: The weight of the steak.
        jsonPath: .spec.steak.weight
      - name: Cooking
        type: string
        description: How would you like your steak?
        jsonPath: .spec.steak.cookLevel
      - name: Fat
        type: string
        description: The amout of fat i.e. how juiy the steak will be.
        jsonPath: .spec.steak.fat

