apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: courses.events.training.sap
spec:
  group: events.training.sap
  version: v1
  scope: Namespaced
  names:
    plural: courses
    singular: course
    kind: Course
  validation:
    openAPIV3Schema:
        properties:
            spec:
              required:
              - training
              properties:
                training:
                  type: object
                  required:
                  - name
                  - participants
                  properties:
                    name:
                      type: string
                    participants:
                      type: integer
