apiVersion: v1
kind: Pod
metadata:
  name: princess-peach
  labels:
     location: castle
spec:
  volumes:
  - name: index-html
    emptyDir: {}
  initContainers:
  - name: setup
    image: busybox
    command:
    - /bin/sh
    - -c
    - echo Hi there, I'm Princess Peach and I'm at my castle at the moment! > /work-dir/index.html
    volumeMounts:
    - name: index-html
      mountPath: "/work-dir"
  containers:
  - name: nginx
    image: nginx:mainline
    ports:
    - containerPort: 80
    volumeMounts:
    - name: index-html
      mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: direct-line-to-peach
spec:
  selector:
    location: castle
  ports:
  - port: 80
    targetPort: 80


