---
persistence:
  enabled: true
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true
ingress:
  enabled: true
  labels:
    # gardener injects let's encrypt certs
    garden.sapcloud.io/purpose: managed-cert
  path: /
  hosts:
    - INGRESS_HOSTNAME_SHORT
    - INGRESS_HOSTNAME_LONG
  tls:
  - secretName: grafana-tls
    hosts:
    - INGRESS_HOSTNAME_SHORT
    - INGRESS_HOSTNAME_LONG
sidecar:
  dashboards:
    enabled: true
grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  explore:
    enabled: true
