apiVersion: v1
kind: ServiceAccount
metadata:
 name: loadbalancer-patch
 namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancer-patch
rules:
- apiGroups: [""]
  resources: ["services","services/status"]
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loadbalancer-patch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loadbalancer-patch
subjects:
- kind: ServiceAccount
  name: loadbalancer-patch
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-patch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: loadbalancer-patch
  template:
    metadata:
      labels:
        app: loadbalancer-patch
    spec:
      serviceAccountName: loadbalancer-patch
      containers:
        - image: elsonrodriguez/minikube-lb-patch:0.1
          imagePullPolicy: IfNotPresent
          name: loadbalancer-patch
