apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: nginx.ingress.dev01.k8s-train.shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - backend:
          serviceName: mynginx
          servicePort: 80
  tls:
  - hosts:
    - nginx.ingress.dev01.k8s-train.shoot.canary.k8s-hana.ondemand.com
    secretName: nginx-ingress-tls
