---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reviews-app-ingress
  labels:
    garden.sapcloud.io/purpose: managed-cert
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.app" . | indent 4}}
spec:
  rules:
  - host: "{{ .Values.Ingress.ShortName }}.{{ .Values.Ingress.Domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: reviews-app-service
          servicePort: 80
  - host: "{{ .Values.Ingress.LongName }}.{{ .Values.Ingress.Domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: reviews-app-service
          servicePort: 80
  tls:
  - hosts:
    - "{{ .Values.Ingress.ShortName }}.{{ .Values.Ingress.Domain }}"
    - "{{ .Values.Ingress.LongName }}.{{ .Values.Ingress.Domain }}"
    secretName: reviews-tls-secret 
