---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ads-db-access
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.db" . | indent 4}}
spec:
  podSelector:
    matchLabels: 
    {{- include "labels.reviews.db" . | indent 6}}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels: 
        {{- include "labels.reviews.app" . | indent 10}}
  egress: []

