apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: users-db-access
  labels:
    component: "{{ .Release.Name }}-{{ .Values.Db.Component }}"
    module: "{{ .Release.Name }}-{{ .Values.Db.Module }}"
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Db.Component }}"
      module: "{{ .Release.Name }}-{{ .Values.Db.Module }}"
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: "{{ .Release.Name }}-{{ .Values.App.Component }}"
          module: "{{ .Release.Name }}-{{ .Values.App.Module }}"
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: users-app-access
  labels:
    component: "{{ .Release.Name }}-{{ .Values.App.Component }}"
    module: "{{ .Release.Name }}-{{ .Values.App.Module }}"
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.App.Component }}"
      module: "{{ .Release.Name }}-{{ .Values.App.Module }}"
  ingress:
  - from:
    - podSelector:
        matchLabels:
          # can access itself
          component: "{{ .Release.Name }}-{{ .Values.App.Component }}"
          module: "{{ .Release.Name }}-{{ .Values.App.Module }}"
    - podSelector:
        matchLabels:
          # the bulletinboard ads app
          component: ads
          module: app
  egress:
  - to:
    - podSelector:
        matchLabels:
          # can access itself
          component: "{{ .Release.Name }}-{{ .Values.App.Component }}"
          module: "{{ .Release.Name }}-{{ .Values.App.Module }}"
    - podSelector:
        matchLabels:
          # the user db
          component: "{{ .Release.Name }}-{{ .Values.Db.Component }}"
          module: "{{ .Release.Name }}-{{ .Values.Db.Module }}"
    - podSelector:
        matchLabels:
          # the dns server
          k8s-app: kube-dns
      namespaceSelector:
        matchLabels:
          name: kube-system
