---
apiVersion: v1
kind: ConfigMap
data:
  SPRING_PROFILES_ACTIVE: cloud
  VCAP_APPLICATION: '{}'
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ConfigName) }}
  {{- include "labels.users.app" . }}
---
apiVersion: v1
kind: Secret
data:
  VCAP_SERVICES: {{ template "vcap-services.encoded" . }} 
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.SecretName) }}
  {{- include "labels.users.app" . }}
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.App.ServiceName }}
  {{- include "labels.users.app" . }}
spec:
  ports:
  - port: {{ .Values.App.ServicePort }}
    protocol: TCP
    targetPort: users-app
  selector:
{{- include "tags.users.app" . | indent 4 }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.Name) }}
  {{- include "labels.users.app" . }}
spec:
  replicas: {{ .Values.App.ReplicaCount }}
  selector:
    matchLabels:
{{- include "tags.users.app" . | indent 6 }}
  template:
    metadata:
{{- include "labels.users.app" . | indent 4 }}
    spec:
      initContainers:
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'for i in $(seq 1 200); do nc -z -w3 {{ template "db-connection" . }} {{ .Values.Db.Postgres.Port }} && exit 0 || sleep 3; done; exit 1']
      containers:
      - name: users
        image: "{{ .Values.App.Image }}:{{ .Values.App.ImageTag }}"
        imagePullPolicy: "{{ .Values.App.ImagePullPolicy }}"
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: SPRING_PROFILES_ACTIVE
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ConfigName) }}
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              key: VCAP_APPLICATION
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ConfigName) }}
        - name: VCAP_SERVICES
          valueFrom:
            secretKeyRef:
              key: VCAP_SERVICES
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.SecretName) }}
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 500Mi
        ports:
        - containerPort: {{ .Values.App.TomcatPort }}
          name: users-app
      imagePullSecrets:
      - name: {{ .Values.App.ImageSecret }}
