---
apiVersion: v1
kind: ConfigMap
data:
  PGDATA_VALUE: "{{ .Values.Db.Postgres.MountPath }}/pgdata"
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.Db.ConfigName) }}
  {{- include "labels.users.db" . }}

---
apiVersion: v1
kind: Secret
data:
  POSTGRES_PASSWORD_VALUE: {{ .Values.Db.Postgres.RootPassword | b64enc }}
  initdb_sql_value: {{ template "initdb.encoded" . }}
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.Db.SecretName) }}
  {{- include "labels.users.db" . }}
type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.Db.ServiceName) }}
  {{- include "labels.users.db" . }}
spec:
  ports:
  - port: {{ .Values.Db.Postgres.Port }}
    name: {{ .Values.Db.PortName }}
  clusterIP: None
  selector:
{{- include "tags.users.db" . | indent 4 }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "db-name" . }}
{{- include "labels.users.db" . }}
spec:
  serviceName: {{ template "add-release-name" (dict "dot" . "name" .Values.Db.ServiceName) }}
  replicas: 1
  selector:
    matchLabels:
{{- include "tags.users.db" . | indent 6 }}
  template:
    metadata:
{{- include "labels.users.db" . | indent 4 }}
    spec:
      volumes:
      - name: init
        secret:
          secretName: {{ template "add-release-name" (dict "dot" . "name" .Values.Db.SecretName) }}
          items:
          - key: initdb_sql_value
            path: initdb.sql
      containers:
      - name: users-db-container
        image: "{{ .Values.Db.Postgres.Image -}}:{{- .Values.Db.Postgres.ImageTag }}"
        ports:
        - containerPort: {{ .Values.Db.Postgres.Port }}
          name: {{ .Values.Db.PortName }}
        volumeMounts:
        - name: users-db-volume
          mountPath: {{ .Values.Db.Postgres.MountPath }}
        - name: init
          mountPath: /docker-entrypoint-initdb.d/
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.Db.SecretName) }}
              key: POSTGRES_PASSWORD_VALUE
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.Db.ConfigName) }}
              key: PGDATA_VALUE
  volumeClaimTemplates: 
  - metadata:
      name: users-db-volume
{{- include "labels.users.db" . | indent 4 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.Db.StorageSize }}

