apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-https
  namespace: <your-namespace>
  labels:
    app: nginx-https
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https
  template:
    metadata:
      labels:
        app: nginx-https
    spec:
      volumes:
      - name: tls-secret
        secret:
          secretName: nginx-sec
      - name: nginxconf
        configMap:
          name: nginxconf
      containers:
      - name: nginx
        image: nginx:1.13.6
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: tls-secret
          readonly: true
        - mountPath: /etc/nginx/conf.d
          name: nginxconf
