---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ServiceName) }}
  {{- include "labels.ads.app" . }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: ads-app-port
  selector:
{{- include "tags.ads.app" . | indent 4 }}
  type: ClusterIP
