---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.Ingress.Name) }}
  {{- include "labels.ads.app" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.App.Ingress.Hostname -}} .ingress. {{- .Values.ClusterName -}} . {{- .Values.ProjectName -}} .shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - path: {{ .Values.App.Ingress.Path }}
        backend:
          serviceName: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ServiceName) }}
          servicePort: ads-app-port
