---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.DeploymentName) }}
  {{- include "labels.ads.app" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{- include "tags.ads.app" . | indent 6 }}
  template:
    metadata:
{{- include "labels.ads.app" . | indent 4 }}
    spec:
      volumes:
      - name: ads-app-properties
        secret:
          secretName: {{ template "add-release-name" (dict "dot" . "name" .Values.App.SecretName) }}
          items:
          - key: spring_profile
            path: application-k8s.yml
      imagePullSecrets:
      - name: artifactory
      initContainers:
      - name: check-db-ready
        image: postgres:9.6
        command: ['sh', '-c', 'until pg_isready -h {{ template "db-connection" . }} -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
      - name: ads
        image: {{ .Values.App.Image -}} : {{- .Values.App.ImageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: ads-app-port
        env:
        - name: USER_ROUTE
          valueFrom:
            configMapKeyRef:
              key: user_route_value
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ConfigMap.Name) }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: spring_profiles_active_value
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ConfigMap.Name) }}
        - name: POST_USER_CHECK
          valueFrom:
            configMapKeyRef:
              key: post_user_check_value
              name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.ConfigMap.Name) }}
        volumeMounts:
        - mountPath: /config/
          name: ads-app-properties  
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 800Mi  
