apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "add-release-name" (dict "dot" . "name" .Values.App.NetworkPolicyName) }}
  {{- include "labels.ads.app" . }}
spec:
  podSelector:
    matchLabels:
{{- include "tags.ads.app" . | indent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress 
          component: controller 
          origin: gardener
      namespaceSelector:
        matchLabels:
          name: kube-system  
  egress:
  - to:
    - podSelector:
        matchLabels:
{{- include "tags.ads.db" . | indent 10 }}
    - podSelector:
        matchLabels:
          component: users
          module: app
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
      namespaceSelector:
        matchLabels:
          name: kube-system

