---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ads-app-config-envs
  labels:
    component: ads
    module: app
data:
  user_route: http://users-service/bulletinboard-users-service
  profile: k8s
  post_user_check: "false"
  
