---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-app
  labels:
    component: ads
    module: app
spec:
  replicas: 3
  selector:
    matchLabels:
      component: ads
      module: app
  template:
    metadata:
      labels:
        component: ads
        module: app
    spec:
      volumes:
      - name: ads-app-properties
        configMap:
          name: ads-app-config-files
      imagePullSecrets:
      - name: artifactory
      containers:
      - name: ads
        image: cc-k8s-course.docker.repositories.sap.ondemand.com/k8s/bulletinboard-ads:latest
        ports:
        - containerPort: 8080
          name: ads-app
        env:
        - name: USER_ROUTE
          valueFrom:
            configMapKeyRef:
              key: user_route_value
              name: ads-app-config-envs
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: spring_profiles_active_value
              name: ads-app-config-envs
        - name: POST_USER_CHECK
          valueFrom:
            configMapKeyRef:
              key: post_user_check_value
              name: ads-app-config-envs 
        volumeMounts:
        - mountPath: /config/
          name: ads-app-properties    
