---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ads-app-config-files
  labels:
    component: ads
    module: app
data:
  application-k8s.yml: "---\nspring:\n  datasource:\n    url: jdbc:postgresql://ads-db-0.ads-db-headless:5432/ads\n    username: adsuser\n    password: initial\n    driverClassName: org.postgresql.Driver\n    driver-class-name: org.postgresql.Driver\n"
