---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-app
  labels:
    component: ads
    module: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ads
      module: app
  template:
    metadata:
      labels:
        component: ads
        module: app
    spec:
      imagePullSecrets:
      - name: artifactory
      containers:
      - name: ads
        image: cc-k8s-course.docker.repositories.sap.ondemand.com/k8s/bulletinboard-ads:latest
        ports:
        - containerPort: 8080
          name: ads-app
        env:
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              key: vcap_services
              name: ads-app-config
        - name: USER_ROUTE
          valueFrom:
            configMapKeyRef:
              key: user_route
              name: ads-app-config
