---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ads-app-configmap
  labels:
    component: ads
    module: app
data:
  reviews_host: <URL to Reviews-Ingress>
  reviews_host_internal: http://reviews-reviews-app-service
  postgres_url: jdbc:postgresql://ads-db-statefulset-0.ads-db-service:5432/postgres
  
