apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: bulletinboard-ads
version: 0.1.1
dependencies:
- name: bulletinboard-users
  repository: file://../../../users/helm/bulletinboard-users/
  version: 0.1.1
  import-values:
  - child: App
    parent: UsersApp
