{
 "title": "Training Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Network Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster IP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_service_spec_type{type=\"ClusterIP\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Node Ports",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_service_spec_type{type=\"NodePort\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Load Balancers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_service_spec_type{type=\"LoadBalancer\",namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "No. of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Pod stats per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 2, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "pods on {{instance}}" },
    { "expr": "kube_node_status_capacity_pods", "legendFormat": "limit of {{node}}" }
   ]
  },
  { "title": "Pods Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Pods scheduled",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pods not running",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 3, "y": 15 },
   "targets": [
    {
     "expr": "(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\"} != 0) "
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Deployments with Replicas",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Statefulsets with Replicas",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{namespace=~\"$namespace\"}"
    }
   ]
  },
  { "title": "Persistent Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Persistent Volume Claims",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes"
    }
   ]
  },
  {
   "title": "Disk usage Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 34 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".+-prometheus-server\"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\".+-prometheus-server\"}) / (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".+-prometheus-server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk usage Grafana",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 39 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".+-grafana\"} - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\".+-grafana\"}) / (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".+-grafana\"}) * 100"
    }
   ]
  }
 ]
}