---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db-credential-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Db.Component }}"
    module: "{{ .Release.Name }}-{{ .Values.Db.Module }}"
type: Opaque
data:
  PG_PASSWORD: {{ .Values.Db.Postgres.RootPassword }}
