---
apiVersion: v1
kind: Service
metadata:
  name: ads-service
  labels:
    component: ads
    module: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: ads-app
  selector:
    component: ads
    module: app
  type: ClusterIP
