---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reviews-app-configmap
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.app" . | indent 4}}
data:
  postgres_url: postgres://postgres@reviews-db-statefulset-0.reviews-db-service:5432/postgres
  
