---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reviews-db-service
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.db" . | indent 4}}
spec:
  ports:
  - port: 5432
    name: reviews-db-port
  clusterIP: None
  selector: {{- include "labels.reviews.db" . | indent 4}}
