---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reviews-db-secret
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.db" . | indent 4}}
type: Opaque
stringData:
  postgres_password: UKII724JK3KN



