---
apiVersion: v1
kind: Service
metadata:
  name: reviews-app-service
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.app" .| indent 4 }}
spec:
  ports:
  - port: 80
    targetPort: reviews-appport
  selector: {{- include "labels.reviews.app" . | indent 4}}
  type: ClusterIP
