---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reviews-app-secret
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.app" . | indent 4}}
type: Opaque
stringData:
  postgres_url: postgres://postgres:UKII724JK3KN@{{ .Release.Name }}-reviews-db-statefulset-0.{{ .Release.Name }}-reviews-db-service:5432/postgres
  
