---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-app-deployment
  labels:
    {{- include "labels.resources" . | indent 4}}
    {{- include "labels.reviews.app" . | indent 4}}
spec:
  replicas: 2
  selector:
    matchLabels: {{- include "labels.reviews.app" . | indent 6}}
  template:
    metadata:
      labels: {{- include "labels.reviews.app" . | indent 8}}
    spec:
      imagePullSecrets:
      - name: {{ .Values.App.ImagePullSecret}}
      initContainers:
      - name: check-db-ready
        image: postgres:9.6
        command: ['sh', '-c',
          'until pg_isready -h reviews-db-statefulset-0.reviews-db-service -p 5432 -U postgres;
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: reviews-app-container
        image: {{ .Values.App.Image | quote }}
        ports:
        - containerPort: 9090
          name: reviews-appport
        env:
        - name: PORT
          value: "9090"
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              key: postgres_url
              name: reviews-app-secret
